### ISSUE TITLE
cost_models format

### ISSUE THREAD

**Issue by 1000101** [input-output-hk/cardano-db-sync#724]
Hi, I've noticed that the current format/type of `cost_models` in `epoch_param` table is somewhat weird and could have been transformed into a valid JSON. Therefore I wanted to ask if this was in fact intended. Thanks!

```
 fromList [(PlutusV1,"fromList [( ...
```

**Comment by erikd** [comment]
It is not valid JSON. This is almost certainly fixed in a PR I am merging today.

Also this is on the `master` branch. If you want to run `db-sync` you should do so from a release tag.

**Comment by mmahut** [comment]
This looks still like an issue on `alonzo-purple-1.0.1`. What commit does this fix?

**Comment by mmahut** [comment]
Confirming this is still an issue on current `master` as well.

**Comment by erikd** [comment]
This is still open: https://github.com/input-output-hk/cardano-db-sync/issues/652
