### ISSUE TITLE
Error: insertShelleyBlock(Alonzo)The block hash 43617264616e6f2e... is missing from the DB

### ISSUE THREAD

**Issue by 0xtrossets** [input-output-hk/cardano-db-sync#953]
**OS**
Your OS:
Docker UBUNTU (cardano-rosetta)

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 11.0.4
PostgreSQL version: 12

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: docker build (cardano-rosetta)

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): docker run (cardano-rosetta)

**Additional context**
cardano-rosetta 1.4.0 and 1.5.0. Same issue on either.

Running a private devnet. Nodes are running fine. This issue only occurs in this devnet. Running mainnet or testnet works fine.

`db-sync` goes into a crash loop with this error. 
Block hash in the error message is always the same?? 
I've tried changing the values for `TestAllegraHardForkAtEpoch`, `TestMaryHardForkAtEpoch`, `TestAlonzoHardForkAtEpoch`, but still happening.
`TestShelleyHardForkAtEpoch` is set to 0

```
[db-sync-node:Info:67] [2021-11-15 22:34:00.03 UTC] Starting chainSyncClient
[db-sync-node:Info:67] [2021-11-15 22:34:00.04 UTC] Cardano.Db is empty
[db-sync-node:Info:72] [2021-11-15 22:34:00.04 UTC] Running DB thread
[db-sync-node:Info:72] [2021-11-15 22:34:00.04 UTC] Rolling back to genesis
[db-sync-node:Info:72] [2021-11-15 22:34:00.04 UTC] No blocks need to be deleted
[db-sync-node:Info:72] [2021-11-15 22:34:00.05 UTC] Found snapshot file for genesis
[db-sync-node.Subscription:Notice:61] [2021-11-15 22:34:00.05 UTC] Identity Required subscriptions started
[db-sync-node:Info:75] [2021-11-15 22:34:00.06 UTC] getHistoryInterpreter: acquired
[db-sync-node:Info:72] [2021-11-15 22:34:00.06 UTC] thisIsAnUglyHack: Main thead
[db-sync-node:Info:82] [2021-11-15 22:34:00.06 UTC] Running Offline fetch thread
[db-sync-node:Info:72] [2021-11-15 22:34:00.06 UTC] Starting at epoch 0
[db-sync-node:Info:72] [2021-11-15 22:34:00.06 UTC] Handling 0 stakes for epoch 0 slot 0, hash 0c998b4e7470b3786f7d26bc78b47b4eded40948281d123be95323eca15647be
[db-sync-node:Error:72] [2021-11-15 22:34:00.07 UTC] Error: insertShelleyBlock(Alonzo)block hash 43617264616e6f2e446253796e632e4572612e5368656c6c65792e47656e657269632e426c6f636b2e626c6f636b5072657648617368
[db-sync-node:Info:72] [2021-11-15 22:34:00.07 UTC] Shutting down DB thread
```

Note that the genesis block hash is the same as what is given by the ledger, so the issue seems to be on the db-sync side.
```
{
    "epoch": 0,
    "hash": "0c998b4e7470b3786f7d26bc78b47b4eded40948281d123be95323eca15647be",
    "slot": 0,
    "block": 0,
    "era": "Alonzo",
    "syncProgress": "100.00"
}
```

**Comment by 0xtrossets** [comment]
Running `12.0.0-pre2`, the error message has a bit more information:
```
[db-sync-node:Info:56] [2021-11-15 05:06:08.51 UTC] Starting at epoch 0
[db-sync-node:Info:56] [2021-11-15 05:06:08.51 UTC] Handling 0 stakes for epoch 0 slot 0, hash 77aa5735b6a5de649f45539d455bc0c89cd949fc77f6e6a41d81f29ec25fc4d4
[db-sync-node:Error:56] [2021-11-15 05:06:08.52 UTC] Error: insertShelleyBlock(Alonzo)The block hash 43617264616e6f2e446253796e632e4572612e5368656c6c65792e47656e657269632e426c6f636b2e626c6f636b5072657648617368 is missing from the DB.
[db-sync-node:Info:56] [2021-11-15 05:06:08.52 UTC] Shutting down DB thread
```

The extra bit is `is missing from the DB`

**Comment by 0xtrossets** [comment]
Looks like the error is defined here https://github.com/input-output-hk/cardano-db-sync/blob/d6f5ccd4937e9597586c8cd9178f4d25cb1bc427/cardano-db/src/Cardano/Db/Error.hs#L35

**Comment by erikd** [comment]
This seems to be an issue with your devnet.

**Comment by 0xtrossets** [comment]
@erikd The devnet itself is running normally. What exactly do you think is the issue with it?

**Comment by erikd** [comment]
I have no idea what the issue other than there is a block missing from the database.

**Comment by 0xtrossets** [comment]
@erikd okay, so why do you think it's an issue with the devnet and not an issue with cardano-db-sync?

**Comment by 0xtrossets** [comment]
Note that the hash it claims is missing is always the same, even if the chain is run from genesis with completely different blocks.

**Comment by 0xtrossets** [comment]
Also another interesting point: The hash that it claims is missing is very long at 108 chars, longer than the normal 64 char hash for blocks 🤔

**Comment by harmangakhal** [comment]
This seems like the same issue I described in https://github.com/input-output-hk/cardano-db-sync/issues/954, even has the same hash. I included my setup for the private network in that issue.

**Comment by erikd** [comment]
@harmangakhal  I agree this is likely the same issue, but it does not manifest on mainnet or any of the testnets that I regularly test `db-sync` on. That means there is almost certainly something wrong with your devnet setup.

**Comment by erikd** [comment]
> Also another interesting point: The hash that it claims is missing is very long at 108 chars, longer than the normal 64 char hash for blocks

All block hashes should be **exactly** 32 bytes (64 characters when encoded as hex) long. If they are not this length, then something is badly wrong.

**Comment by 0xtrossets** [comment]
@erikd 
Could it have something to do with the fact that our devnets all start Shelley era from epoch 0? 
Does db-sync have some expectation that the chain must start in Byron?

**Comment by 0xtrossets** [comment]
> > Also another interesting point: The hash that it claims is missing is very long at 108 chars, longer than the normal 64 char hash for blocks
> 
> All block hashes should be **exactly** 32 bytes (64 characters when encoded as hex) long. If they are not this length, then something is badly wrong.

This exact same 108 char hash is seen not just in many different devnets I've tested with completely different blocks, but also in the one seen by @harmangakhal - 
The error is seen as soon as db-sync tries to begin since from 0. This leads me to believe that there is something wrong within db-sync, as we are not providing this 108 char block at any point.

**Comment by harmangakhal** [comment]
I queried the db,
```
select encode(hash, 'hex') from block

791eea9b752df434b388739807203808c1052e9ac5b2e4707a7357f2fce905c0
5368656c6c65792047656e6573697320426c6f636b2048617368200000000000
```

the shelley genesis hash wasn't matching `configuration.yaml` but I noticed the hex was readable
```
# cardano-cli byron genesis print-genesis-hash --genesis-json ...
ByronGenesisHash: 791eea9b752df434b388739807203808c1052e9ac5b2e4707a7357f2fce905c0
# cardano-cli genesis hash --genesis ...
ShelleyGenesisHash: ac08505207b5b14fc6283716354b6c59d8113352f07f801b4c4b7cd269b67e82
AlonzoGenesisHash: 50c2f9c5d0955b1c535f8ebea57e3291ffb70f1be8a0f6a291a8d89532a2e2c4
```
Looks like it's using hardcoded values,
`5368656c6c65792047656e6573697320426c6f636b2048617368200000000000` is `Shelley Genesis Block Hash`
https://github.com/input-output-hk/cardano-db-sync/blob/689253c7736dfdf2d1f63e05b692313817b9b1bd/cardano-db-sync/src/Cardano/DbSync/Era/Shelley/Genesis.hs#L270
and 
`43617264616e6f2e446253796e632e4572612e5368656c6c65792e47656e657269632e426c6f636b2e626c6f636b5072657648617368` is `Cardano.DbSync.Era.Shelley.Generic.Block.blockPrevHash`
https://github.com/input-output-hk/cardano-db-sync/blob/689253c7736dfdf2d1f63e05b692313817b9b1bd/cardano-db-sync/src/Cardano/DbSync/Era/Shelley/Generic/Block.hs#L164

**Comment by 0xtrossets** [comment]
Nice find @harmangakhal !
From my understanding a fix will need to be put in place? or is there a way to quickly patch it locally to get it running?

**Comment by 0xtrossets** [comment]
@erikd do you have any insights on why this hardcoded value is being looked up and how this issue can be resolved?

**Comment by kderme** [comment]
This has been fixed in https://github.com/input-output-hk/cardano-db-sync/pull/864/commits/59eb2cdd72e65eb40f629ea22941f09c87e4855b#. 

Version 11 does not support testnets which initiate funds and delegations in the shelley networks, but next releases will.

**Comment by 0xtrossets** [comment]
@kderme 
I've tested with version `12.0.0-pre5` and I still see the same error.
Can you reopen this issue?

**Comment by kderme** [comment]
Oh sorry, I thought this was fixed. Any chance you can share the config you're using?

**Comment by 0xtrossets** [comment]
@kderme 
Do you mean the config for the nodes? if so, here it is: https://gist.github.com/0xtrossets/dc9fdff4f716638164010ca683b5259e

It mostly comes from https://github.com/input-output-hk/cardano-node/tree/master/scripts

**Comment by kderme** [comment]
I think there was some regression with this, because it worked for a short period. Fix is in https://github.com/input-output-hk/cardano-db-sync/pull/963

**Comment by 0xtrossets** [comment]
It's working now. Thanks @kderme

**Comment by harmangakhal** [comment]
@0xtrossets Does it continue to sync after a few epochs? It seems to stop syncing at epoch 2 for me. No errors, just repetitive debug logs,
```
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:59] [2021-11-22 19:28:10.10 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Bearer Receive Start: length 1052
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:59] [2021-11-22 19:28:10.10 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Bearer Receive End: length 1052
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:59] [2021-11-22 19:28:10.10 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Bearer Receive Header Start
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:59] [2021-11-22 19:28:10.10 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Bearer Receive Start: length 8
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:69] [2021-11-22 19:28:10.10 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Channel Receive End on (MiniProtocolNum 5) 1052
cardano-db-sync-extended_1  | [db-sync-node.ChainSync:Debug:69] [2021-11-22 19:28:10.10 UTC] fromList [("kind",String "Recv"),("msg",Object (fromList [("agency",String "ServerAgency TokNext TokMustReply"),("kind",String "MsgRollForward")]))]
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:69] [2021-11-22 19:28:10.10 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Channel Send Start on (MiniProtocolNum 5) 2
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:69] [2021-11-22 19:28:10.10 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Channel Send End on MiniProtocolNum 5
cardano-db-sync-extended_1  | [db-sync-node.ChainSync:Debug:69] [2021-11-22 19:28:10.10 UTC] fromList [("kind",String "Send"),("msg",Object (fromList [("agency",String "ClientAgency TokIdle"),("kind",String "MsgRequestNext")]))]
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:69] [2021-11-22 19:28:10.10 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Channel Receive Start on MiniProtocolNum 5
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:58] [2021-11-22 19:28:10.10 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Bearer Send Start: ts: 0x276a71b5 (MiniProtocolNum 5) InitiatorDir length 2
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:58] [2021-11-22 19:28:10.10 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Bearer Send End
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:59] [2021-11-22 19:28:10.10 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Bearer Receive End: length 8
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:59] [2021-11-22 19:28:10.10 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Bearer Receive Header End: ts: 0x276a7253 (MiniProtocolNum 5) ResponderDir len 2
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:59] [2021-11-22 19:28:10.10 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Bearer Receive Start: length 2
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:59] [2021-11-22 19:28:10.10 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Bearer Receive End: length 2
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:59] [2021-11-22 19:28:10.11 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Bearer Receive Header Start
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:59] [2021-11-22 19:28:10.11 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Bearer Receive Start: length 8
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:69] [2021-11-22 19:28:10.11 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Channel Receive End on (MiniProtocolNum 5) 2
cardano-db-sync-extended_1  | [db-sync-node.ChainSync:Debug:69] [2021-11-22 19:28:10.11 UTC] fromList [("kind",String "Recv"),("msg",Object (fromList [("agency",String "ServerAgency TokNext TokCanAwait"),("kind",String "MsgAwaitReply")]))]
cardano-db-sync-extended_1  | [db-sync-node.Mux:Debug:69] [2021-11-22 19:28:10.11 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Channel Receive Start on MiniProtocolNum 5
```

@kderme I tried restarting the docker container (master branch image) in an attempt to resolve the above issue but it seems to error with,
```
cardano-db-sync-extended_1  | Connecting to network specified in configuration.yaml
cardano-db-sync-extended_1  | [db-sync-node:Info:6] [2021-11-22 19:28:54.36 UTC] Schema migration files validated
cardano-db-sync-extended_1  | [db-sync-node:Info:6] [2021-11-22 19:28:54.36 UTC] Running database migrations
cardano-db-sync-extended_1  | [db-sync-node:Info:6] [2021-11-22 19:28:54.36 UTC] Enviroment variable DbSyncAbortOnPanic: False
cardano-db-sync-extended_1  | [db-sync-node:Info:6] [2021-11-22 19:28:54.91 UTC] Using byron genesis file from: "/config/byron/genesis.json"
cardano-db-sync-extended_1  | [db-sync-node:Info:6] [2021-11-22 19:28:54.91 UTC] Using shelley genesis file from: "/config/shelley/genesis.json"
cardano-db-sync-extended_1  | [db-sync-node:Info:6] [2021-11-22 19:28:54.91 UTC] Using alonzo genesis file from: "/config/shelley/genesis.alonzo.json"
cardano-db-sync-extended_1  | [db-sync-node:Info:6] [2021-11-22 19:28:54.91 UTC] NetworkMagic: 42
cardano-db-sync-extended_1  | [db-sync-node.db-sync:Debug:6] [2021-11-22 19:28:54.91 UTC] SELECT "block"."id"
cardano-db-sync-extended_1  | FROM "block"
cardano-db-sync-extended_1  | WHERE "block"."hash" = ?
cardano-db-sync-extended_1  | ; [PersistByteString "}}^f}\222u\198\247\&1s\222N\US\130>mylM\158\221\DC2\133r\141\190\171C\255\&4\144"]
cardano-db-sync-extended_1  | [db-sync-node.db-sync:Debug:6] [2021-11-22 19:28:54.91 UTC] SELECT "meta"."id", "meta"."start_time", "meta"."network_name", "meta"."version"
cardano-db-sync-extended_1  | FROM "meta"
cardano-db-sync-extended_1  | ; []
cardano-db-sync-extended_1  | [db-sync-node.db-sync:Debug:6] [2021-11-22 19:28:54.91 UTC] SELECT COUNT(*)
cardano-db-sync-extended_1  | FROM "tx"
cardano-db-sync-extended_1  | WHERE "tx"."block_id" = ?
cardano-db-sync-extended_1  | ; [PersistInt64 1]
cardano-db-sync-extended_1  | [db-sync-node.db-sync:Debug:6] [2021-11-22 19:28:54.91 UTC] SELECT SUM("tx_out"."value")
cardano-db-sync-extended_1  | FROM "tx_out" INNER JOIN "tx" ON "tx"."id" = "tx_out"."tx_id" INNER JOIN "block" ON "tx"."block_id" = "block"."id"
cardano-db-sync-extended_1  | WHERE "block"."previous_id" IS NULL
cardano-db-sync-extended_1  | ; []
cardano-db-sync-extended_1  | [db-sync-node:Info:6] [2021-11-22 19:28:54.91 UTC] Initial genesis distribution present and correct
cardano-db-sync-extended_1  | [db-sync-node:Info:6] [2021-11-22 19:28:54.91 UTC] Total genesis supply of Ada: 10020.000000
cardano-db-sync-extended_1  | [db-sync-node.db-sync:Debug:6] [2021-11-22 19:28:54.91 UTC] SELECT "block"."id"
cardano-db-sync-extended_1  | FROM "block"
cardano-db-sync-extended_1  | WHERE "block"."hash" = ?
cardano-db-sync-extended_1  | ; [PersistByteString "Shelley Genesis Block Hash \NUL\NUL\NUL\NUL\NUL"]
cardano-db-sync-extended_1  | [db-sync-node:Info:6] [2021-11-22 19:28:54.91 UTC] Validating Genesis distribution
cardano-db-sync-extended_1  | [db-sync-node.db-sync:Debug:6] [2021-11-22 19:28:54.91 UTC] SELECT "meta"."id", "meta"."start_time", "meta"."network_name", "meta"."version"
cardano-db-sync-extended_1  | FROM "meta"
cardano-db-sync-extended_1  | ; []
cardano-db-sync-extended_1  | [db-sync-node.db-sync:Debug:6] [2021-11-22 19:28:54.91 UTC] SELECT COUNT(*)
cardano-db-sync-extended_1  | FROM "tx"
cardano-db-sync-extended_1  | WHERE "tx"."block_id" = ?
cardano-db-sync-extended_1  | ; [PersistInt64 2]
cardano-db-sync-extended_1  | Error: Shelley.validateGenesisDistribution: Expected initial block to have 1 but got 2
```
I can open a new issue if it's unrelated.

**Comment by 0xtrossets** [comment]
@harmangakhal 
Mine is working normally for now.
Have you made sure you remove all docker volumes before restarting? Is the actual devnet running properly (past epoch 2)?

**Comment by harmangakhal** [comment]
> @harmangakhal Mine is working normally for now. Have you made sure you remove all docker volumes before restarting? Is the actual devnet running properly (past epoch 2, check by querying with cardano-cli or similar)?

Thanks for the update, I restart the entire private net using `docker-compose down -v` but in the example above `Error: Shelley.validateGenesisDistribution: Expected initial block to have 1 but got 2` comes from just restarting the container as I figured it probably supports basic functionality to start/stop an instance. The node continues to produce blocks and I can even submit a transaction, 
```
bash-4.4# cardano-cli query tip --testnet-magic 42
{
    "epoch": 8,
    "hash": "f0cb11f201c62159832ad2dd7d33b1055b5ea978caffca73e4a3527bc7f20c02",
    "slot": 4414,
    "block": 150,
    "era": "Shelley",
    "syncProgress": "100.00"
}
```. It seems to consistently just stop syncing after epoch 1 / at 36 blocks.

**Comment by kderme** [comment]
@harmangakhal what is the config and genesis files of your net?

**Comment by harmangakhal** [comment]
> @harmangakhal what is the config and genesis files of your net?

Config: https://gist.github.com/harmangakhal/143a69d2d9ed5101a1d434c5aaaa99d1
Shelley: https://gist.github.com/harmangakhal/4003888e3408194d1aa3f87ad4ace598
Byron: https://gist.github.com/harmangakhal/48447a583ec356e6082cc446ee7ee211
Alonzo: https://gist.github.com/harmangakhal/a4eb5e1504cbb07cee0379b149fd11b3

My setup: https://github.com/input-output-hk/cardano-db-sync/issues/954#issue-1053216884

**Comment by kderme** [comment]
This pr should fix this case https://github.com/input-output-hk/cardano-db-sync/pull/972

**Comment by harmangakhal** [comment]
Thanks @kderme your PR seems to have resolved the issue with restarting, but db-sync seems to still stop syncing after an epoch. If I restart it an additional epoch will be persisted to the postgresql database but it stops syncing again. There doesn't seem to be any errors logged. Do you have any idea what might be going wrong or how I might go about resolving this?

**Comment by 0xtrossets** [comment]
@kderme Looks like your fix was reverted at some point and it is now appearing again in 12.0.x

Can you apply the fix again and release a new patch?
